#ifndef EMBEDDEDSHELLWINDOW_GLOBAL_H
#define EMBEDDEDSHELLWINDOW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EMBEDDEDSHELLWINDOW_LIBRARY)
#  define EMBEDDEDSHELLWINDOW_EXPORT Q_DECL_EXPORT
#else
#  define EMBEDDEDSHELLWINDOW_EXPORT Q_DECL_IMPORT
#endif

#endif // EMBEDDEDSHELLWINDOW_GLOBAL_H
